version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server #look the above Dockerfile in this directory
        volumes: 
            - /app/node_modules
            - ./server:/app #everytime you look for something in app directory go to server directory server is reference to app file
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379 #these are default in redis doc in docker hub
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DATABASE=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
